### ISSUE TITLE
Some families in $genome.mod.EDTA.TElib.fa but missed in $genome.fa.mod.EDTA.TEanno.gff and $genome.fa.mod.EDTA.TEanno.sum

### ISSUE THREAD

**Issue by YTLogos** [oushujun/EDTA#100]
Hi @oushujun 
After the annotation of TEs I summary families and superfamilies I found some TE_family (TE_00007558_INT (Copia) in my example) is in the $genome.mod.EDTA.TElib.fa but missed in in $genome.fa.mod.EDTA.TEanno.gff and $genome.fa.mod.EDTA.TEanno.sum files. Can you please clarify what caused this inconsistency? Thanks!

Best,
Tao

**Comment by oushujun** [comment]
Dear Tao,

This is normal. The TE library always has a large fraction of redundancy
even we try to remove redundant copies. The 80-95-80 rule was used in this
process being 95 is the coverage of sequences. For sequences that follow
under this rule, they will be kept in the library as different TEs.
However, when doing repeatmasking, the program will just pick the hit that
generates the "best" alignment, so some library sequences are not picked
due to the information redundancy in the library.

Best,
Shujun

**Comment by YTLogos** [comment]
Ok, I get it now, Thanks!
