### ISSUE TITLE
How to find TIR in novel species by EDTA

### ISSUE THREAD

**Issue by 1Wencai** [oushujun/EDTA#128]
Hi
Thanks for developing the EDTA.
We know zero about TIR in yeast. So we don't have curatedlib about TIR in yeast.
I am using EDTA to find TIR in novel species(yeast),following is the code :

`/home/zhangwencai/EDTA/EDTA.pl -genome /data/zhangwencai/reference/pombe.ASM294v2.29.dna.toplevel.fa -species others -step all -sensitive 1 -t 14 -anno 1`

TEanno.gff3  contains the TIR identified by homology and structural, I don't kown how does EDTA work to find TIR, so I can't understand the result of TEanno.gff3 about TIR.
 I looked up the literature on TIR-learner, which contains 3 modules. The first module and second module use " a library of TE reference" ,In my EDTA program, if there is a " a library of TE reference" ?
Could you fix up my question? This will help me to understand the result of TEanno.gff3 about TIR.

best
wencai

**Comment by oushujun** [comment]
Hi Wencai,

Not sure I understand your question. For TIR-Learner, if no library is provided, then only module 3, the de novo TIR identification module, is executed. I am not a yeast biologist, but I think you should be able to find curated yeast TEs from a variety of resources such as https://www.yeastgenome.org/ and studies like: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3511429/. Without a curated library, you still can identify TEs from the yeast genome de novo.

Hope these helps. Please let me know if you have further questions.

Best,
Shujun

**Comment by sanyalab** [comment]
Hi Shujun,

Expanding this specific question, the curated library that you mention, does it have to be from the line that one is trying to annotate? For example lets say

I have a manually curated TE library from Line A of Cotton. I am trying to annotate Line B. Can I provide Line A TE library directly using the --curatedLib flag? OR do I need to create a curated TE library for Line B first.

Thanks
Abhijit

**Comment by 1Wencai** [comment]
Hi Abhijit
In my understanding，It depends on the similarity of Line A of Cotton and Line B，Most of the time，you need to create a curated TE library for Line B first. Because curated TE library needs to be very accurate.

best
wencai

**Comment by oushujun** [comment]
I understand curated TEs are highly valuable resources and not all species have it. If your species happen to have such resources, the `--curatedlib` option can make use of such high-quality TE knowledge. It is encouraged to have your own curation of TEs, either in part or in full, especially for the TEs that are the main subjects in your research project. For your own curation, you can run EDTA without `--curatedlib`, then curated the structurally intact de novo TEs in the `EDTA.raw` directory.

You can use curated TEs from a sister species or from another lineage of the same species, but TEs in your species will be named based on TE names in the curated library, given any matches that pass the renaming threshold. If your curated TEs are evolutionarily distant from your species, then it's likely they don't contribute too much to your TE annotation due to the lack of sequence homology.

Shujun

**Comment by 1Wencai** [comment]
Thanks for solving my problem

**Comment by sanyalab** [comment]
Hi Shujun,

I am still a little fuzzy on how the --curatedLib feature gets used. If we give libraries from Repbase or some other source for a particular species or its close relative to EDTA, how do these repeats appear in the final TElib.fa? When you say that these repeats are incorporated "as is" in the final TElib, do you mean
1) the final TElib will contain them these repeats given by --curatedlib parameter without any modification OR
2) In the final TElib, homologs of the repeats specified by the --curatedlib parameter will be present.

Lastly, If I want repeatmasker to use the Repbase database to predict homology based repeats, do I specify that with the --curatedlib parameter?

Thanks
Abhijit
