### ISSUE TITLE
Lots of unknowns

### ISSUE THREAD

**Issue by fungal-spore** [oushujun/EDTA#159]
Hi,
EDTA found lots of unknown TEs, just wondering what would have flagged these as TEs in the first place if they have unknown? Repeat content? I want to be able to say something like "TEs categorized as unknown were classed as TEs based on....."

I attempted to upload image here of parse results, hopefully it came through ok. Thanks!

![image](https://user-images.githubusercontent.com/52299431/108198103-713cf800-70d8-11eb-8e97-871d9167746d.png)

**Comment by oushujun** [comment]
Hi,

EDTA uses structural features to identify intact TEs at the beginning. For example, if a sequence has terminal repeat and satisfied a number of related features, then it's classified as LTR retrotransposons. Then EDTA will try to classify TEs into superfamilies, ie Gypsy and Copia, based on coding features, otherwise will be named LTR/unknown. 

If you use the `--sensitive 1` option, then RepeatModeler2 will be recruited to identify repetitive sequences that were not reported by the structural module of EDTA. Due to the lack of homology and coding features, most of them are named unknown/unknown. We have lower confidence in these categories so you may want to filter them with more measures, eg. copy number, overlap with genes, etc.

Best,
Shujun
