### ISSUE TITLE
Non-matching between EDTA.TEanno.gff3 and EDTA.TEanno.sum statistics

### ISSUE THREAD

**Issue by rubenzaragoza** [oushujun/EDTA#174]
Hi Shujun Ou,

I am using the EDTA software to analyze TEs in plants. The analysis ran great. However, when I compared the results of the annotation gff3 and summary file the counts of gff3 not matched the summarized statistics. I counted the total TEs, and for each chromosome, but I can not link the gff3 and the summary file.
For example, the scaffold_12 has 16 entries of TEs in the gff3, but 17 TEs are reported in the summary file. This is the same for all the chromosomes and scaffolds.

**eg.: scaffold_12:**

**gff3 file:**
scaffold_12     EDTA    Copia_LTR_retrotransposon       2866    5334    19009   +       .       ID=TE_homo_208810;Name=TE_00003273_INT;Classification=LTR/Copia;Sequence_ontology=SO:0002264;Identity=0.923;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       5335    7628    14805   +       .       ID=TE_homo_208811;Name=TE_00001936_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.795;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       8435    8682    14805   +       .       ID=TE_homo_208812;Name=TE_00001936_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.795;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       8659    12627   17878   +       .       ID=TE_homo_208813;Name=TE_00004567_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.893;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       11615   12003   11435   -       .       ID=TE_homo_208814;Name=TE_00004025_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.823;Method=homology
scaffold_12     EDTA    LTR_retrotransposon     12004   13901   10910   +       .       ID=TE_homo_208815;Name=TE_00003778_INT;Classification=LTR/unknown;Sequence_ontology=SO:0000186;Identity=0.873;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       12623   14676   5953    +       .       ID=TE_homo_208816;Name=TE_00004567_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.798;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       13902   14238   11435   -       .       ID=TE_homo_208817;Name=TE_00004025_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.823;Method=homology
scaffold_12     EDTA    Copia_LTR_retrotransposon       14711   15090   1972    -       .       ID=TE_homo_208818;Name=TE_00004553_INT;Classification=LTR/Copia;Sequence_ontology=SO:0002264;Identity=0.854;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       16609   17212   2783    +       .       ID=TE_homo_208819;Name=TE_00001936_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.89;Method=homology
scaffold_12     EDTA    Copia_LTR_retrotransposon       17329   17992   4929    -       .       ID=TE_homo_208820;Name=TE_00004553_INT;Classification=LTR/Copia;Sequence_ontology=SO:0002264;Identity=0.924;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       18039   18503   2830    +       .       ID=TE_homo_208821;Name=TE_00001936_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.934;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       18504   19918   10616   -       .       ID=TE_homo_208822;Name=TE_00004025_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.932;Method=homology
scaffold_12     EDTA    Gypsy_LTR_retrotransposon       19920   20866   5985    +       .       ID=TE_homo_208823;Name=TE_00002110_LTR;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.881;Method=homology
scaffold_12     EDTA    Copia_LTR_retrotransposon       20867   22697   14574   +       .       ID=TE_homo_208824;Name=TE_00003273_INT;Classification=LTR/Copia;Sequence_ontology=SO:0002264;Identity=0.934;Method=homology
scaffold_12     EDTA    Copia_LTR_retrotransposon       22698   22926   1090    +       .       ID=TE_homo_208825;Name=TE_00004344_LTR;Classification=LTR/Copia;Sequence_ontology=SO:0002264;Identity=0.822;Method=homology

**sum file:**

Seq            Count      bpMasked
=====          =====      ========
             Bd2   40789      21103171
             Bd3   41623      21458464
     **scaffold_12   17         17540**
             Bd4   36051      18506916
 Bd1_centromere_   87         32272
     scaffold_14   2          11983
             Bd1   52218      25722601
             Bd5   20506      11702772

In addition, when I count the TEs per class neither match the counts.

I saw that this is a recurrent issue but I think that it keeps without resolving the doubt.

What is the most confident file to save the statistics, TEanno.gff3 or TEanno.sum?

Why some types of annotation such as "e.g.: Bd5:28147489..28151509" appear on the TEanno.gff3 file but not in the TEib.fa file, which only includes the TE_xxxxxxx annotation-type? Are the annotations type "Bd5:28147489..28151509" include in the summary counts?

I would appreciate it if you can shed light on these questions.

Thanks in advance.

Best
Rubén

**Comment by oushujun** [comment]
Hi Rubén,

Thank you for providing the example for discussions. You just found the difficulty and uncertainty in the area of TE annotation. So far it is still challenging to estimate the copy number of TE sequences. This is due to many reasons: 1. the degradation of the element itself making the boundaries fuzzy. 2. recombination activities and nested insertion of other elements complicating the arrangement of the original element. 3. native similarity between different TEs also confuses the homology-based annotation. 4. other reasons I have not realized... So it's pretty common that two or many TE annotation entries overlapping each other. Your example also has such a phenomenon. 

The summary file was produced by a script adapted from RepeatMasker, which is another TE annotation program that also tries to resolve the overlapping issue, but I am afraid it's not perfect. Neither of these programs is perfect. For your case as an example, probably the script decided to trim overlaps into different elements and thus making new pseudo-copies in the result. (i.e., the third entry below is nested within the second entry).

>scaffold_12	EDTA	LTR_retrotransposon	12004	13901	10910	1898	.	ID=TE_homo_208815;Name=TE_00003778_INT;Classification=LTR/unknown;Sequence_ontology=SO:0000186;Identity=0.873;Method=homology
scaffold_12	EDTA	Gypsy_LTR_retrotransposon	12623	14676	5953	2054	.	ID=TE_homo_208816;Name=TE_00004567_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.798;Method=homology
scaffold_12	EDTA	Gypsy_LTR_retrotransposon	13902	14238	11435	337	.	ID=TE_homo_208817;Name=TE_00004025_INT;Classification=LTR/Gypsy;Sequence_ontology=SO:0002265;Identity=0.823;Method=homology

With these complications, my philosophy is to preserve what aligns best with the library sequence and allow overlapping between entries, so that both nested insertions and annotation uncertainty information is preserved. If you prefer each bp is annotated only once, there is a split.gff3 in the EDTA.anno folder that tries to achieve the purpose. But again, the count of entry number does not represent the copy number of this family in your genome.

With too much uncertainty in counting copy numbers, I recommend using the count of total bps instead, and you may use the sum file to sum up the bps to avoid double-counting. The gff3 file is very helpful when you try to combine other genome-wide data types and in a genome browser. 

For annotations with a coordinate as ID, those are structurally annotated TEs and lacking a significant number of copies in the genome to form a "family". They are mostly single or just a few copies for that sequence genome-wide. Thus, they are not collected in the TE library.

Please let me know if you have more questions.

Best,
Shujun

**Comment by rubenzaragoza** [comment]
Hi Shujun,

Thank you very much for your detailed answer. You have improved my understanding of the TE annotation.
So, If I understand good, the most accurate statistics are in the sum file.

**Is it possible to get the summary file but showing the statistics per chromosome and TE family?

The current sum file is:**

Class                  Count        bpMasked    %masked
=====                  =====        ========     =======
LTR                    --           --           --
    Copia              11275        11396310     4.21%
    Gypsy              33044        34389487     12.70%
    unknown            2681         1814904      0.67%
TIR                    --           --           --
    CACTA              9763         5112883      1.89%
    Mutator            12161        4124174      1.52%
    PIF_Harbinger      6288         2216556      0.82%
    Tc1_Mariner        45502        11555036     4.27%
    hAT                3610         874459       0.32%
nonLTR                 --           --           --
    LINE_element       396          217177       0.08%
nonTIR                 --           --           --
    helitron           63910        25935982     9.58%
repeat_region          2663         918751       0.34%
                      ---------------------------------
    total interspersed 191293       98555719     36.40%

---------------------------------------------------------
Total                  191293       98555719     36.40%

**and per chromosome:**

Seq            Count      bpMasked
=====          =====      ========
             Bd2   40789      21103171
             Bd3   41623      21458464
     scaffold_12   17         17540
             Bd4   36051      18506916
 Bd1_centromere_   87         32272
     scaffold_14   2          11983
             Bd1   52218      25722601
             Bd5   20506      11702772

**But, it would be great if I would be able to know the "count" and "bpMasked" per TE family and chromosome:

Example:**

Chromsome Bd2:
Copia --> counts = xxx; bpMasked = xxx
Gypsy --> counts = xxx; bpMasked = xxx
CACTA --> counts = xxx; bpMasked = xxx
PIF_Harbinger --->counts = xxx; bpMasked = xxx
...
Chromsome Bd3:
Copia --> counts = xxx; bpMasked = xxx
Gypsy --> counts = xxx; bpMasked = xxx
CACTA --> counts = xxx; bpMasked = xxx
PIF_Harbinger --->counts = xxx; bpMasked = xxx
...
...

**Is it possible to compute the statistics type showed above?**

Thank you very much for your time and explications.

All the best,
Rubén

**Comment by rubenzaragoza** [comment]
Hi Shujun,

I think that the information that I need is stored in the folder "mod.EDTA.anno", in the file called ".mod.EDTA.TEanno.out". I think that the summary (.sum) file is constructed using the .out file and in this file is store the coordinates, strand, chromosome, TE classification, TE name, and others (see below):

e.g.
10000 0.001 0.001 0.001 BhD1 101 412 NA - TE_00001964 nonTIR/helitron
10000 0.001 0.001 0.001 BhD1 774 878 NA - TE_00001964 nonTIR/helitron
10000 0.001 0.001 0.001 BhD1 1016 1102 NA - TE_00001964 nonTIR/helitron
10000 0.001 0.001 0.001 BhD1 1175 1360 NA - TE_00001964 nonTIR/helitron
10000 0.001 0.001 0.001 BhD1 1435 1545 NA - TE_00001964 nonTIR/helitron
...

I think that I can extract the approximate amount of copies of TE and the length ((start - end coordinate)+ 1) of the TEs, for each chromosome and TE superfamily using this file. Thus, these statistics will match summary (.sum) statistics.

Could you confirm my thoughts about this?

Thank you very much.

best,

Rubén

**Comment by oushujun** [comment]
Hi Rubén,

Yes you are right, that the sum file is produced from the ".mod.EDTA.TEanno.out" file. To make per chromosome summaries, you can extract per chromosome annotations in the anno.out file and use the buildSummary script to make sum file for each chromosome:

`$buildSummary = "$script_path/util/buildSummary.pl";`
`perl $buildSummary -maxDiv 40 -genome_size $genome_size -seq_count $seq_count $genome.EDTA.TEanno.out > $genome.EDTA.TEanno.sum`

You need to provide chromosome size instead of genome size in this process. seq_count is the number of sequence in the .out file, so should be 1 for one chromosome.

Best,
Shujun

**Comment by rubenzaragoza** [comment]
Great!
Thank you very much for solving my doubts.

All the best,

Rubén
