### ISSUE TITLE
getDataset.py Failed to import module

### ISSUE THREAD

**Issue by 111-dep** [oushujun/EDTA#192]
Hello,
During the TIR search, I encountered the following problems:
Traceback (most recent call last):
  File "/home/tangjs/miniconda3/share/EDTA/bin/TIR-Learner2.5/Module3_New/getDataset.py", line 12, in <module>
    from tensorflow.python.keras.utils import to_categorical
ImportError: cannot import name 'to_categorical' from 'tensorflow.python.keras.utils'

Could you tell me how to solve this kind of mistake? I didn't find the relevant solution.
Thank you very much for your help.

**Comment by oushujun** [comment]
Delete the current conda repository and reinstall EDTA.

Shujun

**Comment by kdm9** [comment]
The actual solution to this is that EDTA requires tensorflow==1.14 so make sure your conda/mamba env has this version

**Comment by oushujun** [comment]
@kdm9 Thank you for your contribution. The `EDTA.yml` file does specify tensorflow==1.14. I need to double-check the bioconda recipe tho, but it should be also specified because this tensorflow version is key to running TIR-Learner  - one of the component in EDTA.

**Comment by kdm9** [comment]
So the conda meta.yml in the bioconda recipes repo [seems to specify `tensorflow==1.14`](https://github.com/bioconda/bioconda-recipes/blob/0e86699fa13d0a7529d493db45fd80280b1d0f42/recipes/edta/meta.yaml#L29), but when I installed it with `mamba install -c bioconda edta`, a modern tensorflow was installed. I'm not sure if this is because the package in the actual bioconda repo is out of date with respect to the, or if there was an issue with dependency resolution. It was in a new clean conda env though. `mamba install -c bioconda -c conda-forge edta tensorflow=1.14 h5py<3 python=3.7` worked though.

**Comment by 111-dep** [comment]
Hello, guys,Your email was sent in groups.

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "oushujun/EDTA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [oushujun/EDTA] getDataset.py Failed to import module (#192)





 
So the conda meta.yml in the bioconda recipes repo seems to specify tensorflow==1.14, but when I installed it with mamba install -c bioconda edta, a modern tensorflow was installed. I'm not sure if this is because the package in the actual bioconda repo is out of date with respect to the, or if there was an issue with dependency resolution. It was in a new clean conda env though. mamba install -c bioconda -c conda-forge edta tensorflow=1.14 h5py<3 python=3.7 worked though.
