### ISSUE TITLE
Differences in results with --rmout vs with EDTA library

### ISSUE THREAD

**Issue by sarjopp** [oushujun/EDTA#193]
I am annotating a bunch of newly sequenced hymenoptera genomes. I am trying to wrap my head around the huge difference in my results when using EDTA "normally" versus supplying my own homology-based library. I am running RepeatMasker (with a library generated from RepBase and DFAM) like so:
1) RepeatMasker alone:
RepeatMasker -pa 9 -s -nolow -norna -dir . -xsmall -gff -species hexapoda -html -source -lcambig atriplicis_genome.fasta

2) "normal" EDTA:
perl EDTA.pl --genome atriplicis_genome.fasta --species others --step all --cds GCF_009193385.2_Nvit_psr_1.1_NC_045757.1.CDS.fa --anno 1 --evaluate 1 --threads 6

3) EDTA with the RepeatMasker output:
perl EDTA.pl --genome atriplicis_genome.fasta --species others --step all --cds GCF_009193385.2_Nvit_psr_1.1_NC_045757.1.CDS.fa --anno 1 --evaluate 1 --threads 6  --rmout atriplicis_repeatmasker.out

I am consistently getting MUCH lower estimates of repetitive content with approach 3 and I do not understand why. I have tried to walk through exactly what is happening, but doing side-by-side comparison of the two sets of EDTA outputs is making me tear out my hair.

If anyone has any thoughts or insights, I would be most grateful!

Thanks,
Sara

<img width="377" alt="Screen Shot 2021-06-01 at 8 27 58 PM" src="https://user-images.githubusercontent.com/12255653/120406100-142c2180-c318-11eb-944f-f7a389975d5d.png">

**Comment by oushujun** [comment]
Hi, first of, you should not provide the pfam/repbase RepeatMasked file to
EDTA. You need to use the EDTA-generated library to generate the out file
instead. The --rmout function is to skip the internal masking process to
save time.  .out files from other libraries will not be recognized
properly.

With many genomes, You need to be aware of the quality differences. EDTA is
a de novo approach, If TEs in the genome are not well assembled, then it
can't identify enough good quality TEs for complete annotation. You may
generate a pan-genome library by combining individual libraries to
compensate genome quality differences.

To compare annotations, You can use the --evaluate results.

Best,
Shujun

**Comment by sarjopp** [comment]
Thank you for your reply but I'm afraid I am more confused than ever. The EDTA usage states "  --rmout	[File]	Provide your own homology-based TE annotation instead of using the EDTA library for masking. File is in RepeatMasker .out format. This file will be merged with the structural-based TE annotation. (--anno 1 required). Default: use the EDTA library for annotation." This does not seem to match what you said above. I understood rmout to be a way to COMBINE my own homology-based results with EDTA's results. Can you please clarify further? This issue has derailed my pipeline.

**Comment by sarjopp** [comment]
And if it is the case that rmout is not a way of combining my own homology-based TE annotation with the EDTA results, can you suggest a different way of doing so?

**Comment by oushujun** [comment]
Sorry, I think using other homology based annotation is not fully tested.
You may provide the library for homology annotation to EDTA with
--curatedlib

**Comment by oushujun** [comment]
I tested the program with `--rmout` using external homology annotations, and EDTA actually handled it well with some requirements. First, the naming of TEs needs to follow the RepeatMasker format and recognizable by the conversion file: `EDTA/util/TE_Sequence_Ontology.txt`, otherwise the unrecognizable TEs will be labeled as `repeat_region` and you will receive a bunch of warning messages. Second, the provided `.out` file needs to be comprehensive because it represents the homology annotation of this genome. The final annotation is structural + homology, and if the provided homology annotation is incomplete, for example, annotated using a different species TE library, the resulting final annotation will also be incomplete.

For your combination of RepeatMasker `.out` and EDTA intact annotation, I don't know why the resulting TE content is even lower. I may need the sequence and .out files to reproduce and debug.

Shujun

**Comment by sarjopp** [comment]
Dear Shujun, if you can help me figure this out it would be a great
kindness! Looking at the names in my .out file, everything seems okay. But
my results (decrease in identified repeats) when using the RepeatMasker
.out with EDTA make no sense. In case you have time and interest, I am
attaching my genome, .out, and CDS files.
 A_atri_genome.fasta
<https://drive.google.com/file/d/17bAdQ5FBUtMMeGaGLzI4Bv-cSeh3jiM4/view?usp=drive_web>
 A_atri_genome.fasta.out
<https://drive.google.com/file/d/1Lm0OvBDEilVfwcPyLyCt2guRWhVttw00/view?usp=drive_web>
 GCF_009193385.2_Nvit_psr_1.1_NC_045757.1.CDS.fa
<https://drive.google.com/file/d/1jfpNyOBcAHBIR0Z-u71yTHo8lfMYYoiG/view?usp=drive_web>
Genome: A_atri_genome.fasta
CDS: GCF_009193385.2_Nvit_psr_1.1_NC_045757.1.CDS.fa
RepeatMasker out: A_atri_genome.fasta.out

My RepeatMasker command:
RepeatMasker -pa 9 -s -nolow -norna -dir . -xsmall -gff -a -species
hexapoda -html -source -lcambig A_atri_genome.fasta

My EDTA command:
perl /nas4/CG2/soppenheim/miniconda3/envs/EDTA/bin/EDTA.pl \
--genome A_atri_genome.fasta --species others --step all \
--cds GCF_009193385.2_Nvit_psr_1.1_NC_045757.1.CDS.fa \
--anno 1 --evaluate 1 --threads 6

**Comment by oushujun** [comment]
Thanks for sharing. I can take a look but may need sometime. -Shujun

**Comment by sarjopp** [comment]
Thanks!

**Comment by sarjopp** [comment]
Hi Shujun, have you had a chance to look into this?

Thank you,
Sara

**Comment by oushujun** [comment]
Hi Sara,

Sorry for late. I have got the data and submitted jobs in the server, but I
have not got the chance to check the results yet. I will get back to you
later.

Shujun

**Comment by oushujun** [comment]
Hi Sara,

Sorry for the long delay. I finally get the chance to look at your genome. It runs well and the percentage (27.96%) is pretty close to your results. When I add your RM.out file, the resulting total percentage did drop to a very low value (~3%). I checked the code, it ran correctly. 

What I noticed is the RM.out file you provided, which has very very low bit scores (the first column) that indicates alignment confidentiality. This is likely due to the use of inter-specific TE libraries/database for the annotation. In EDTA, the min bit score (`-minscore`) was set to 300, and other parameters such as divergence (`-maxdiv`) and minimal length (`-minlen`) are also used to filter out low-quality alignments. So basically the entire external RM.out file was filtered out and only intact TEs were survived to the final summary.

If you can find confident parameters to filter entries in the RM.out file, you may hand-code the filtering parameters yourself on line 642 of `EDTA.pl`.
`perl $make_masked -genome $genome -rmout $genome.out -maxdiv 30 -minscore 300 -minlen 80 -hardmask 1 -misschar N -threads $threads -exclude $exclude`

Best,
Shujun

**Comment by sarjopp** [comment]
Thank you, Shujun. I understand your point about the low scores in the
RepeatMasker output--I'm sorry I didn't think to check that myself. I still
think it would be nice if EDTA could automatically COMBINE external
annotations with the EDTA output--in this case, admittedly that would have
been pointless but with a better RepeatMasker output it would be useful.

Many thanks,
Sara

**Comment by oushujun** [comment]
Hi Sara,

I think the answer is yes. If you provide an external repeatmasker output to EDTA, then the homology annotation by the EDTA library is suppressed. The final result will be the external RM annotation + intact TEs by EDTA.

The pitfall of doing this: if the self-provided RM result is not comprehensive, the resulting annotation will not be comprehensive. There is no extra homology annotation if an external RM result is provided. In your case all of the provided RM annotations were filtered out, so the final result contains only intact TEs.

Best,
Shujun
