### ISSUE TITLE
Does EDTA benefit from using the RepBase archive for RepeatMasker

### ISSUE THREAD

**Issue by andreaswallberg** [oushujun/EDTA#199]
Dear @oushujun & Co,

Will those with access to RepBaseRepeatMaskerEdition-20181026.tar.gz and possibility to rebuild the RepeatMasker database benefit from using this archive for repeat annotation within EDTA?

**Comment by oushujun** [comment]
Maybe. It depends. If it does, it would not be a direct benefit.

RepeatMasker in EDTA is always using the custom library mode, so the built-in database will always be ignored. If you have a RepBase and want to use it on your species, you may extract the data sequence and provide it to EDTA via `--curatedlib`. Although, I am not sure what is the quality of RepBase for those non-model species (ie., non-rice/human/drosophila/arabidopsis, etc). You should be cautious about the quality of anything provided via `--curatedlib`.

Another way to benefit the annotation is via `--force 1`. For some species (eg., fungi #188), you need to use `--force 1` to overwrite errors due to the lack of certain TE superfamilies (eg, LTR), then EDTA will use rice TEs (`EDTA/database/rice6.9.5.liban`) to replace the missing part so that EDTA can move forward. This is far from perfect. If there is a closer TE database in RepBase than rice, you may use it to replace the rice ones for better annotations. A simple way is to put your lib in /database/ then rename it to `rice6.9.5.liban`.

Shujun

**Comment by andreaswallberg** [comment]
Hi again!

These are perfectly good pieces of advice. I am working on crustaceans and I think all repeat annotations, except for perhaps Daphnia, are automated and none of them carefully curated. I suppose re-using non-curated libraries for de novo annotation is not a good idea, right?

**Comment by oushujun** [comment]
No - most likely You will suffer from the mistakes People made previously.
Although, You may check out #198 for salvaging potentially good stuffs. -
Shujun
