### ISSUE TITLE
Any suggestions for helitron filtering?

### ISSUE THREAD

**Issue by conniecl** [oushujun/EDTA#206]
Hi, shujun.
So exacting we finally have such amazing tools for TE annotation!!! 
When using EDTA to annotate my genome (plant, ~1Gb), I get ~16% Helitron, closer to the Copia (7.99%) +Gypsy (12.48%). I noticed in your paper you have suggested to treat Helitron carefully which makes me think a further filtering are needed. After checking the issues, found you have provided some suggestions in #90.  
Since sedge family only 1 genome have been assemblied, it's difficult for me to filter the helitron based on sister species. And I think the PCR verification may not suit with my situation since I found ~90% Helitron are predicted by homology, which means it introduce by RepeatModeler and RepeatMasker? Is there any suggestions to filter the Helitrons based on something like coverage and identity? Or just remain the 'structural' based helitrons? By the way, how can I stringency the homology searching procedure? It obvious the finally TE set will positively related to the structural annotation result (Pearson: 0.998 in my case, regardless Gypsy and Copia).

Best wishes~

**Comment by oushujun** [comment]
Hello,

Thanks for using EDTA and read the other related issues. Without a sister
species, you may still compare the boundaries of candidate helitrons within
your genome, but this time you need to find as much dissimilarity as
possible for flanking sequences of candidates of the same family.
Otherwise, if the boundaries are similar, they are likely false positives
(why?)

You may curate intact helitrons and start with the most repetitive
families.

helitrons are all from EDTA. Those identified by RepeatModeler are labeled
as unknown repeat_region.

Reading the original HelitronScanner paper may help.

Best,
Shujun
