### ISSUE TITLE
Problem with Unstranded TEs

### ISSUE THREAD

**Issue by hswhitbeck** [oushujun/EDTA#224]
Hello,

We are running the EDTA program and we are having an issue with the intact file produced in the output. It seems that the intact file does contain DNA transposons, but none of them are stranded. We are wondering why none of them are stranded? Also, there is a big difference in the percentage of unstranded DNA TEs in the intact file compared to the other file (not intact) produced by EDTA. Additionally, within the stranded TEs, many of the TEs do not have long open reading frames. Could you please explain to us how EDTA determines the strandedness for the TEs? 

Thank you,
Hunter

**Comment by oushujun** [comment]
Hi Hunter,

Sorry for the delayed reply. The direction (mainly LTR) is mainly determined by coding regions within a TE. If there is no ORF found, or ORFs found with confounding directions, then the direction of this TE will not be determined and labeled as "?" or ".". For DNA transposons, all intact TEs were unstranded by default, due to the lack of HMM profiles that can be used to determine the direction. If a TE does not have any ORF but has copies with ORFs that can be used to determine the direction, then this TE's direction can be inferred. There are still many things to do with TE strandedness.

Best,
Shujun

**Comment by hswhitbeck** [comment]
Hello Shujun,

Thank you for your response. This information is very useful.

Best,
Hunter
