### ISSUE TITLE
EDTA and LTR insertion time

### ISSUE THREAD

**Issue by setri100** [oushujun/EDTA#233]
Hey @oushujun,

big fan of EDTA and LTR_retriever here! For my plant genomes, the EDTA output .fasta.mod.EDTA.intact.gff3 file gives me way more LTR transposons than LTR_retriever and LTR_harvest. Is that an expected behavior since EDTA also includes fragmented LTRs?
And is there a way I can use the LTR results from EDTA to calculate the LTR insertion time using LTR_retriever?

Cheers from Germany!

**Comment by oushujun** [comment]
Hello @setri100,

Sorry for the delayed response. And thank you for supporting LTR_retriever and EDTA!!

To answer your questions, there shouldn't be more LTRs from EDTA results than LTR_retriever, because those were derived from LTR_retriever results. You may need to look into the lines and not all lines represent LTRs. The GFF3 is organized like genes, which breaks down each intact LTR-RTs into different features. Other than that, the ".fasta.mod.EDTA.intact.gff3" file also contains other intact TEs such as TIRs and Helitrons. You may `grep LTR_retrotransposon *.fasta.mod.EDTA.intact.gff3|less -S` to get only intact LTRs. Or go to the folder `*mod.EDTA.raw/LTR/` to look for `*mod.pass.list` which is the direct output of LTR_retriever.

For intact LTR information in EDTA results, you can find the identity info from the last column of the gff3 file. You can use this to calculate the age yourself, with T = K / 2µ = (1 - identity) / 2µ, where µ is the mutation rate of your species in the unit of per bp per year. By default, LTR_retriever uses µ = 1.3e-8 from rice.

Hope this helps!

Best,
Shujun

**Comment by dcf774967** [comment]
> Hello @setri100,
> 
> Sorry for the delayed response. And thank you for supporting LTR_retriever and EDTA!!
> 
> To answer your questions, there shouldn't be more LTRs from EDTA results than LTR_retriever, because those were derived from LTR_retriever results. You may need to look into the lines and not all lines represent LTRs. The GFF3 is organized like genes, which breaks down each intact LTR-RTs into different features. Other than that, the ".fasta.mod.EDTA.intact.gff3" file also contains other intact TEs such as TIRs and Helitrons. You may `grep LTR_retrotransposon *.fasta.mod.EDTA.intact.gff3|less -S` to get only intact LTRs. Or go to the folder `*mod.EDTA.raw/LTR/` to look for `*mod.pass.list` which is the direct output of LTR_retriever.
> 
> For intact LTR information in EDTA results, you can find the identity info from the last column of the gff3 file. You can use this to calculate the age yourself, with T = K / 2µ = (1 - identity) / 2µ, where µ is the mutation rate of your species in the unit of per bp per year. By default, LTR_retriever uses µ = 1.3e-8 from rice.
> 
> Hope this helps!
> 
> Best, Shujun

Hello @oushujun 
What's dif between *TEanno.gff3 and *intact.gff3?
Which file should I use if I want to get the LTR insertion time?

Thank you for your reply ！  --zcf

**Comment by oushujun** [comment]
Hi @dcf774967,

Please read the [Q&A](https://github.com/oushujun/EDTA/wiki/Making-sense-of-EDTA-usage-and-outputs---Q&A) and there should be answers to your questions. `ltr_identity` is the field you need.

**Comment by dcf774967** [comment]
> 
Thank you! sir. 
I get it.

**Comment by bijendrabio** [comment]
> Hello [@setri100](https://github.com/setri100),
> 
> Sorry for the delayed response. And thank you for supporting LTR_retriever and EDTA!!
> 
> To answer your questions, there shouldn't be more LTRs from EDTA results than LTR_retriever, because those were derived from LTR_retriever results. You may need to look into the lines and not all lines represent LTRs. The GFF3 is organized like genes, which breaks down each intact LTR-RTs into different features. Other than that, the ".fasta.mod.EDTA.intact.gff3" file also contains other intact TEs such as TIRs and Helitrons. You may `grep LTR_retrotransposon *.fasta.mod.EDTA.intact.gff3|less -S` to get only intact LTRs. Or go to the folder `*mod.EDTA.raw/LTR/` to look for `*mod.pass.list` which is the direct output of LTR_retriever.
> 
> For intact LTR information in EDTA results, you can find the identity info from the last column of the gff3 file. You can use this to calculate the age yourself, with T = K / 2µ = (1 - identity) / 2µ, where µ is the mutation rate of your species in the unit of per bp per year. By default, LTR_retriever uses µ = 1.3e-8 from rice.
> 
> Hope this helps!
> 
> Best, Shujun

@oushujun Is there a difference between Divergence plot generated by EDTA using Kimura 2-parameter (K2P) distance (range 1 to 40), and the insertion time calculated use the aforementioned formula?

**Comment by oushujun** [comment]
Here's an option to recalculate LTR age using the K2P model: https://github.com/cwb14/TESS/blob/main/PrinTE/bin/seq_divergence.py
