### ISSUE TITLE
To get the reverse transcriptase sequence

### ISSUE THREAD

**Issue by pxxiao-hz** [oushujun/EDTA#235]
Hello, I am currently doing phylogenetic analysis of gypsy and copia transposons. I used the result of `EDTA mod.LTR.intact.gff3`.
I use the reverse transcriptase sequences of gypsy and copia from [GyDB](https://gydb.org/index.php?title=Collection_HMM) as queries, and use tblastn to align them to `copia.intact.fa` and `gypsy.intact.fa`, respectively. But, I found that some LTRs do not have hits.
I don't know where the problem is. Or do you have any suggestions for obtaining the reverse transcriptase sequences of intact LTR?
Best wishes!
pxxiao

**Comment by oushujun** [comment]
Hi @pxxiao-hz,

It's normal for some LTRs lacking coding sequences. They are still called "intact LTR" by LTR_retriever and EDTA because their boundaries and structural features are present. This is different from autonomous LTR in which you should expect a full set of coding sequences.

You may try [TEsorter](https://github.com/zhangrengang/TEsorter) for your research purpose.

Best,
Shujun
