### ISSUE TITLE
Output difference v.1.9.4 vs. v.2.0.0

### ISSUE THREAD

**Issue by lidijaberke** [oushujun/EDTA#243]
Hi there,

first of all, thank you for the excellent tool. I was comparing the output of v1.9.4 to v2.0.0 for a plant genome. The results are similar, with some more LTRs found and more LTRs that could be classified. The only question mark are the results for Mutator elements: while the total sequence space stayed more or less the same (~62Mb), the total number of elements decreased to 1/3. I could not connect this to any modifications in the changelog (https://github.com/oushujun/EDTA/releases/tag/v2.0.0). Do you have any suggestions for what caused this difference?

Cheers,
Lidija

**Comment by oushujun** [comment]
HI Lidija,

Thank you for using EDTA. There isn't any large change to the filtering mechanisms for 2.0, so the differences you observed are likely due to stochastic changes from run to run. There could be some Mutators misclassified in the first or the second run (most likely both). You may perform some curations or compare with sister taxa to determine which one is better.

Best,
Shujun

**Comment by lidijaberke** [comment]
Hi Shujun,

thank you for the reply. I will run it a few more times to see the range of differences.

Cheers,
Lidija
