### ISSUE TITLE
questions about EDTA‘s result files

### ISSUE THREAD

**Issue by tinyhys** [oushujun/EDTA#255]
Hi dear developers,
Many thanks for your excellent tools! I have some questions.
1. I noticed the outputs in the path labeled with *raw and *intact. Looking into the scripts, the *LTR.raw.fa seemed to be used in the following steps. What's the difference between raw.fa and intact.fa ?

![image](https://user-images.githubusercontent.com/37066354/155457846-c3f420c8-501b-4c17-a756-ccf27c956558.png)

2. By running LTR_retriever separately I got a LTR lib differed from that of EDTA. I would like to use the scripts solo_finder.pl in LTR_retriever to obtain the solo LTR and intact LTR, but it seemed different between the LTR_retriever's *out file and the EDTA's version. Which should I trust?

Looking forward to your reply，
Best !

**Comment by oushujun** [comment]
Hi @tinyhys,

*LTR.raw.fa is the raw LTR library for EDTA, which is copied from *LTRlib.fa generated by LTR_retriever. *LTR.intact.fa contains all intact LTR sequences, which is redundant.

solo_finder.pl works for LTR_retriever outputs and you may need to modify it to work on EDTA outputs.

Shujun

**Comment by tinyhys** [comment]
Hi Shujun, 
Thanks to your reply and I have other questions wishing your comments. 
Do the solo LTRs still have the ability to transposite? And if some of them do, how can I determine whether a solo LTR remaining the transposition activity or not ?
Many thanks!

**Comment by oushujun** [comment]
Hi @tinyhys,

Good question. The current understanding is not: Solo LTRs are incapable of transposition. But who knows. Since LTR elements are retrotransposons, they require reverse transcription to make new copies. For LTRs to be able to transpose, they would need to transcribe and make mRNAs. That means, to see if a solo LTR is transposable or not, the first evidence is detecting their mRNAs.

Best,
Shujun

**Comment by tinyhys** [comment]
Dear teacher, thanks a lot for your comment! it solves a concern on my analysis.
