### ISSUE TITLE
Using previously computed RepeatModeler output in EDTA

### ISSUE THREAD

**Issue by Eric-CH-Chen** [oushujun/EDTA#268]
Installation: mamba
As titled, I want to use and/or reuse previously computed RepeatModeler outputs into EDTA instead of having EDTA to run it again.

I am currently having trouble getting the` --sensitive 1` to work. It seems to get stuck at building database aspect of the RepeatModeler step (log just shows that `Died at /home/eric/miniconda3/envs/EDTA_mamba/bin/BuildDatabase`, `RepeatModeler is finished, but no consensi.fa files found.`)

I tried to run RepeatModeler directly to see if it is working in the environment, and it died at the BuildDatabase step

```
Error: Unknown argument: "blastdb_version"
Error:  (CArgException::eInvalidArg) Unknown argument: "blastdb_version"

The command used was: /home/eric/miniconda3/envs/EDTA_mamba/bin/makeblastdb -blastdb_version 4 -out Ti -parse_seqids -dbtype nucl -in ./rkdnyKu2Tv 2>&1
Died at /home/eric/miniconda3/envs/EDTA_mamba/bin/BuildDatabase line 332.
```
Curiously the `makeblastdb` is set at version `2.5.0` vs. `2.10.0` of `rmblastn` and I am unable to use conda/mamba to update them to the correct version. 

I am, however, able to run RepeatModeler locally from another conda environment so I am tempted to use that and feed it into EDTA. How should I make this work? 

Currently going to try copy pasting RM_* output from a different `RepeatModeler` run into the `$genome.fasta.mod.EDTA.final` folder to see if it will work. Will report back when that run is finished.

**Comment by oushujun** [comment]
Hello @Eric-CH-Chen 

The version of RepeatMasker is set in the conda env. You may need to update RepeatMasker so that rmblastn could be updated along. I have not checked if the latest RepeatMasker is compatible with EDTA, but if you don't encounter any errors, that means OK.

To use other RepeatModeler results, you may put the `$genome.RM.consensi.fa` in the $genome.EDTA.final folder and use `--overwrite 0 --sensitive 1`, in this way EDTA will recognize the existing RepeatModeler result and use it. Be sure to generate the RepeatModeler using the EDTA masked (without `--sensitive 1`) genome but not the original genome, otherwise it will contain more false positives than expected.

Shujun

**Comment by Eric-CH-Chen** [comment]
Thank you for the speedy reply! And yes `$genome.RM.consensi.fa` into the $genome.EDTA.final folder worked. Thanks!
