### ISSUE TITLE
Is MITE-Hunter still there?

### ISSUE THREAD

**Issue by aderzelle** [oushujun/EDTA#28]
Hello, 
the bioArxiv paper describes the usef of MITE-Hunter but the new figure on github suggests it's not there any more. If I understand correctly it has been disabled for the moment, right?

**Comment by oushujun** [comment]
Dear @aderzelle,

MITE-Hunter has been removed from the pipeline due to its low performance. The results of MITE-Hunter are mostly covered by TIR-Learner, so we gain faster execution without jeopardizing the sensitivity. For example, in the maize genome, MITE-Hunter only contributes a number of new candidate sequences to the TE library, and these sequences masked a total of 17Kb out of the 2.3Gb genome, which covered only 0.0007% but took hours to run through the MITE-Hunter module.

If you prefer to retain the MITE-Hunter information, you may run the pipeline on your own, then `cat` the results to `genome.TIR.raw.fa` file before moving forward to the next filtering step.

Best,
Shujun

**Comment by aderzelle** [comment]
Okay thanks, 
I don't particularly need Mite-Hunter though I just wanted to be sure. 
Thanks
