### ISSUE TITLE
panEDTA won't run without a cds file

### ISSUE THREAD

**Issue by KevinABird** [oushujun/EDTA#312]
Hi Shujun,

Wonderful work. I tried to use the new panEDTA script on a set of genomes and got an error that a cds file not included and the process was terminated. I was still able to run EDTA on each genome separately, and without a cds file, successfully. Is this something with the panEDTA script and could I somehow get panEDTA to run on the output of the EDTA runs?

Thanks,
Kevin

**Comment by oushujun** [comment]
Hi Kevin,

Yes this is a setting enforced by panEDTA to reduce the noise accumulated by using multiple genomes. You may do one of the following:
1. use CDS from a closely related species 
2. use a first-pass gene prediction from one of the genomes
3. use the Arabidopsis CDS file
4. the toy CDS file in the test folder.

1 and 2 will give you power to remove gene-related sequences in the result; 3 will give you some power to remove conserved genes because Arabidopsis could be distant from your species; 4 is just a bypass solution.

Hope this helps!

Best,
Shujun
