### ISSUE TITLE
Can't load Encode.so

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [oushujun/EDTA#330]
Hi,

I am using the singularity install on an HPC (cannot use conda). The isntall seemed to go ok, but running EDTA gives the error below:

install:

singularity pull EDTA.sif docker://oushujun/edta:2.0.0
INFO:    Converting OCI blobs to SIF format
WARNING: 'nodev' mount option set on /g/data/nm31, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 852e50cd189d done
Copying blob a6236801494d done
Copying blob 679c171d6942 done
Copying blob a547c2c45029 done
Copying blob 472d4a740df7 done
Copying blob 11bced570584 done
Copying blob ae93be0bde06 done
Copying blob 2210efc56b17 done
Copying blob 6ec0e15d839a done
Copying config ae72fe4b04 done
Writing manifest to image destination
Storing signatures
2023/02/06 01:14:06  info unpack layer: sha256:852e50cd189dfeb54d97680d9fa6bed21a6d7d18cfb56d6abfe2de9d7f173795
2023/02/06 01:21:16  warn xattr{etc/gshadow} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2023/02/06 01:21:16  warn xattr{/g/data/nm31/d/tmp/build-temp-061433489/rootfs/etc/gshadow} destination filesystem does not support xattrs, further warnings will be suppressed
2023/02/06 01:24:59  info unpack layer: sha256:a6236801494d5ca9acfae6569427398c2942c031375b96cac887cafe1de5a09b
2023/02/06 01:25:00  warn xattr{etc/gshadow} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2023/02/06 01:25:00  warn xattr{/g/data/nm31/d/tmp/build-temp-061433489/rootfs/etc/gshadow} destination filesystem does not support xattrs, further warnings will be suppressed

2023/02/06 01:29:57  info unpack layer: sha256:679c171d6942954a759f2d3a1dff911321940f23b0cdbe1d186f36bef0025124
2023/02/06 01:32:29  info unpack layer: sha256:a547c2c45029c28e7019e6c652697845a604ffd24e15a0434681a94d49ec1438
2023/02/06 01:32:29  info unpack layer: sha256:472d4a740df7df56e25c99e40be6e521648ace24680e90c5deef6431d23c0bdb
2023/02/06 01:32:29  info unpack layer: sha256:11bced570584cc3addd3d688e317b70e4b874e6ccf7dcdbb450452ca5dbf765d
2023/02/06 01:32:29  info unpack layer: sha256:ae93be0bde0627843640b882447ee91656d2131470f0effc1325625925fd3ac0
2023/02/06 01:32:58  info unpack layer: sha256:2210efc56b17214f9e16e5b2b6683462271d9fd3c877d0ba7e18822dbace3170

2023/02/06 01:45:56  info unpack layer: sha256:6ec0e15d839a3ceb1c159b18d6a2a69f65ca4dfbd99de74b0c19ac78b32b9ba1
INFO:    Creating SIF file...

Error:

singularity exec /g/data/nm31/bin/EDTA.sif EDTA.pl --genome /g/data/nm31/d/r17_nepenthes/r17.2_synteny/ptg000074l.fasta --overwrite --anno 1 --threads 24
Can't load '/home/554/ta0341/perl5/lib/perl5/x86_64-linux-thread-multi/auto/Encode/Encode.so' for module Encode: libperl.so.5.26: cannot open shared object file: No such file or directory at /opt/conda/lib/site_perl/5.26.2/x86_64-linux-thread-multi/XSLoader.pm line 96.
 at /home/554/ta0341/perl5/lib/perl5/x86_64-linux-thread-multi/Encode.pm line 12.
BEGIN failed--compilation aborted at /home/554/ta0341/perl5/lib/perl5/x86_64-linux-thread-multi/Encode.pm line 13.
Compilation failed in require at /opt/conda/lib/5.26.2/Pod/Text.pm line 33.
BEGIN failed--compilation aborted at /opt/conda/lib/5.26.2/Pod/Text.pm line 33.
Compilation failed in require at (eval 2) line 1.
BEGIN failed--compilation aborted at /opt/conda/lib/5.26.2/Pod/Usage.pm line 30.
Compilation failed in require at /opt/conda/share/EDTA/EDTA.pl line 7.
BEGIN failed--compilation aborted at /opt/conda/share/EDTA/EDTA.pl line 7.

**Comment by oushujun** [comment]
Try to clean up your singularity cache and install EDTA again. You may also
try this source:

   1.


   singularity pull EDTA.sif docker://quay.io/biocontainers/edta:2.0.0

Best,
Shujun

**Comment by oushujun** [comment]
Any luck?

**Comment by oushujun** [comment]
Here are some information from ChatGPT:

The error message indicates that there is a missing shared library file needed by the Perl Encode module, which is required by the EDTA.pl script.

Specifically, the error message states that the file /home/554/ta0341/perl5/lib/perl5/x86_64-linux-thread-multi/auto/Encode/Encode.so cannot be loaded, which in turn is because the library libperl.so.5.26 cannot be found.

This could be caused by a few things, such as:

The library is not installed on the system or is not in the search path of the system libraries.
The library was installed in a non-standard location, and the search path needs to be updated to include that location.
The script is running in a different environment with incompatible library versions.
To fix this issue, you can try the following:

Check if the missing library (libperl.so.5.26) is installed on your system. If not, install it using your system package manager.
If the library is installed in a non-standard location, update the search path to include that location using the LD_LIBRARY_PATH environment variable.
Check if the script is running in an environment with incompatible library versions. You may need to update the environment or run the script in a different environment.
For example, you could try the following command to set the LD_LIBRARY_PATH variable and then run the script:

bash
Copy code
export LD_LIBRARY_PATH=/path/to/library:$LD_LIBRARY_PATH
singularity exec /g/data/nm31/bin/EDTA.sif EDTA.pl --genome /g/data/nm31/d/r17_nepenthes/r17.2_synteny/ptg000074l.fasta --overwrite --anno 1 --threads 24
Replace /path/to/library with the directory where the missing library is installed.
