### ISSUE TITLE
some TE sequences in *.mod.EDTA.TElib.fa cannot be found in *.mod.EDTA.TEanno.gff3

### ISSUE THREAD

**Issue by hyma99** [oushujun/EDTA#360]
Hi @oushujun 
Thanks for developing the panEDTA pipline.  I have successfully executed the panEDTA.sh and obtained the final results. However, when I was counting novel TEs, I found that only a portion of TE names could be found in the  *.mod.EDTA.TEanno.gff3. What could be the reason for those novel TEs that cannot be found in the *.mod.EDTA.TEanno.gff3?
Thanks a lot and look forward to your reply

**Comment by oushujun** [comment]
Good observation. This is expected because sequences in the library are not entirely independent to each other, but we use a cutoff (80-90-100) to reduce most of the redundancy. Homology annotation is based on blastn, and the RepeatMasker algorithm will try to find the match that generate the highest alignment score (or similar scores in that regards). Eventually some sequences were not selected in the final annotation.

You may try to remove those not-selected seequences and mask again, and repeat this purging process. It may reduce the sensitivity but you will end up having less sequences not presenting in the final result.

Shujun
