### ISSUE TITLE
Using CDS from multiple species

### ISSUE THREAD

**Issue by bijendrabio** [oushujun/EDTA#465]
Hello @oushujun, Just curious if using the CDS from multiple closely related species will effect the repeat annotation output? 
or Do you suggest removing the redundancy from he concatenated CDS from multiple species before using it for --cds option.
Kindly suggest!

Regards,
B

**Comment by oushujun** [comment]
Hello B,

If your species are closely related, providing just one is sufficient because we expect low changes in gene coding. If you have multiple, use the higher-quality one. Using multiple gene sets may introduce TE sequences in the gene set and reduce your TE annotation sensitivity.

Thanks!
Shujun
