### ISSUE TITLE
Running RepeatModeler separately

### ISSUE THREAD

**Issue by DanJeffries** [oushujun/EDTA#84]
Hi Shujun,

I have run EDTA on my 7.5 Gb assembly and have a curated TE library (hurray!). However I would also like to run RepeatModeler to pick up the non-LTRs in the genome. It is not clear to me exactly how to do this though (i.e. the command to use). I suppose I should pass my existing EDTA output library using the --curatedlib argument, but at what stage should I enter the pipeline so that only RepeatModeller and the appropriate filters are run. Alternatively, could I run RepMod separately, concatenate the two libraries and run EDTA using the --filter flag? 

Thanks

Dan

**Comment by oushujun** [comment]
Hi Dan,

It would be something like: `perl EDTA.pl --genome genome.fa --curatedlib genome.fa.mod.EDTA.TElib.fa --step final --sensitive 1 --anno 1 --rmout genome.fa.mod.out`

The `--step final` step is where RepeatModeler will be executed, and providing the TE library will help to identify new repeats from the RM result. The `--rmout` input is the repeatmasked genome based on the EDTA library, if you have one, so that the program will skip the internal masking step. 

Best,
Shujun

**Comment by DanJeffries** [comment]
Great, thanks Shujun, I'll give it a go! 
Best,
Dan
