### ISSUE TITLE
EDTA flank_filter running long time

### ISSUE THREAD

**Issue by xuleifan** [oushujun/EDTA#93]
Hi Shujun,

I have a problem about EDTA on my 1.4Gb fish genome（similar to #66 ，but did not finished after 7 days in 24-threads）. The repeat is about 54%. I have got TIR-Learner result , but flank_filter has has been running for seven days with 24 cpu. Many blastn are running and do not report errors.  Before, other species had not encountered this problem. 

I just wanted to check if this is normal, and if there is anything I can do to speed this up?

Many thanks

xulei

**Comment by oushujun** [comment]
Hi Xulei,

This sounds normal to me.  Please let me know if you encounter any problems
later on.

Best,
Shujun

**Comment by oushujun** [comment]
@baozg reported that some SSR-rich genomes (especially 2-bp SSRs) may take a long time to finish. TIR candidates with SSR as flanking sequences will trick the program into a dead loop and further escaped the filter. These candidates should be false TIRs. This is a bug and will be fixed in the next update which is foreseen to come within a week. 

#96 may experiencing the similar issue. Sorry for the inconvenience.

Best,
Shujun

**Comment by oushujun** [comment]
The latest update should have this issue fixed. Please reopen the issue if it's not.

Best,
Shujun
