### ISSUE TITLE
EDTA has been running for 25 days and still going

### ISSUE THREAD

**Issue by cgrootcrego** [oushujun/EDTA#96]
Hi,

I have EDTA running on a 1.2 Gb genome which allegedly has a lot of repetitive elements (~ 70 % of the genome). 
This has been running for 25 days now, using the --sensitive option. TIR is very slowly putting input in [genome].fasta.mod.TIR.ext30.fa.cov0.9iden90.tabout file for the past 5 days or so. I'm running this on a cluster with 48 cpus and 200 gb of memory. 
I wanted to know if this running time would be expected in these conditions. Additionally, is it possible to stop the analysis and relaunch it (at the same point I ended it) without the --sensitive tag? 

Thank you!

**Comment by cgrootcrego** [comment]
Maybe I should add that this genome has a bit over 10 000 scaffolds (27 of these are in the MB scale).

**Comment by oushujun** [comment]
Hi,  normally this should be fine.  TIR will be slow if you have a lot of
scaffolds. The sensitive option won't change the TIR speed.  Does your
gemome have a lot of SSRs?  Other user reported the slowdown by SSRs
especially in sealife genomes.  I am working on an update for this
improvement.

Best,
Shujun

**Comment by cgrootcrego** [comment]
Hi Shujun,

Thanks for your answer. According to an analysis by repeatexplorer this genome should mostly have TEs and not so many other repeats. This is a bromeliad plant genome (terrestrial), but we have many indications that it expanded in genome size mostly due to TEs, so maybe that's another reason why it's not going very fast.

Still, it's been 17 days since the final TIR learner gff files were created and the .tabout file only has data for 1570 scaffolds (out of 10 000). It has data for 22 out of 27 large scaffolds. I'm a bit worried if it keeps going at this pace, or will it significantly speed up for shorter scaffolds? 

Thanks!

**Comment by oushujun** [comment]
It doesn't need an overwhelming amount of SSRs to slow down the program. You may want to test out the following script on your genome and see if it improves.
1. download and unzip the file.
[flanking_filter.pl.zip](https://github.com/oushujun/EDTA/files/5009492/flanking_filter.pl.zip)
2. enter the `$genome.mod.EDTA.raw/TIR/` directory and rename the .tabout file to something else.
3. run this command:
`perl flank_filter.pl -genome $genome.mod -query $genome.mod.TIR.ext30.fa -t $threads`
4. If it finishes quickly, great! You will see a new .tabout file. Then you may find the old `flanking_filter.pl` process and kill it:
`kill $(ps aux|grep flanking_filter|awk '{print $2}')`

Hopefully the program will continue with the new .tabout file. And if not, simply replace the `flanking_filter.pl` script in the `EDTA/util/` program directory and rerun `EDTA`.

I am about to release a new version with this fix. I figure you may test if this is the cause, otherwise we need to find it out.

Best,
Shujun

**Comment by cgrootcrego** [comment]
Hi Shujun,

TIR finally finished after 20 days, but we have had some setbacks with our genome (meaning we will have to rerun EDTA on a different version), so I won't be able to test your script just yet. Once we're back on track and at the TE annotation step again I'll try this out (in case it takes very long again) and get back to you. Thanks a lot for your help so far!

**Comment by oushujun** [comment]
Thank you for letting me know. I am sorry you have to rerun everything on
the new assembly. I should be able to release a new version of EDTA next
week or later. Please check for updates when you decide to rerun EDTA.

Best,
Shujun

**Comment by cgrootcrego** [comment]
Hi Shujun,

I wanted to let you know that I reran EDTA on the new version of our assembly and this took in total about 15 days. This was done on a different cluster and with a different version of EDTA (v. 1.8.5, previously 1.7.8). I still don't know what caused EDTA to run so slowly in the first time, but that matter is solved now. In any case, thanks for you help!

Best,
Clara

**Comment by oushujun** [comment]
Hi Clara,

You may pull the latest EDTA (v1.9.0) and execute the patch script `EDTA/util/patch_1.8.3_to_1.9.0.pl` on your existing annotation. You don't need to reinstall the EDTA dependencies. The patch should be done within an hour or so. The new version has better gff3 formats and won't drastically change your existing annotation.

Best,
Shujun
