### ISSUE TITLE
About repeat stats

### ISSUE THREAD

**Issue by biolittleboy** [oushujun/EDTA#98]
Hi, Dr. Ou
I have already got some results with the parameter of `--anno`. Then I found the total length of the repeat sequence cannot be matched in files of '*mod.EDTA.TEanno.sum' and 'mod.EDTA.TEanno.gff'. but I found the total number of repeat is matched in these two files. To solve this problem, I found the length of many repeated sequences is zero when I checked the '*mod.EDTA.TEanno.sum' file. attached please find an example.
Could you please tell me how to  #match in these two files in the total length of the repeat sequences, or why many '0' in '*mod.EDTA.TEanno.sum' file.
![image](https://user-images.githubusercontent.com/41177973/89242195-87e79a00-d633-11ea-9ea2-5dd316d5dc97.png)

**Comment by oushujun** [comment]
Hello @biolittleboy,

Sorry for the delayed response. I looked into my annotations and those 0-bp annotations do exist. If you further visualize them on `IGV` you will see there are overlapping TEs at that location with almost identical coordinates. In such cases, the summary script ([buildSummary.pl](https://github.com/oushujun/EDTA/blob/master/util/buildSummary.pl), adapted from RepeatMasker) decides that only one is needed so it sets one as 0 and counts the other (see an example below). Occasionally you see the two overlapping annotations have different classifications. In some cases, one or both of them could be misclassified and EDTA was not able to decide which one is true. In other cases, one could be a TE nest-inserted into a different TE.

So far the 0 lines are only a few in one genome annotation and I will let them stay until I find a better solution. These lines may affect the exact annotated bp, but won't affect too much about the percentage of each class. You may use the summary in the `.TEanno.sum` file to report your results.

Best,
Shujun

![image](https://user-images.githubusercontent.com/5996084/90083080-2b414a80-dcd7-11ea-9e4c-ceaf93cc6727.png)

**Comment by biolittleboy** [comment]
Hi, Dr. Ou

Thank you so much for your patient explanation. I have visualized my data on the IGV, and as you say, the '0' line sequence is all inside a large sequence. Your answer also solved another problem from `RepeatMasker` for me. I found the result of `buildSummary.pl` is more detailed and accurate than the result from the file of `*tbl`. Did you agree with that?

Another question about EDTA. I have a fragmentary genome with the N50 of 1.5Kb. EDTA's result shows only 18% TE in the genome, but Repeatmasker's result shows that there are 50% TE in the genome. Could you please explain this question, or how can I obtain more TEs from using the software of EDTA.

Thank you again!

**Comment by oushujun** [comment]
RepeatMasker `.tbl` summarize the repeats in the species you specified, and by default it uses Human. So you may see some different TE classes with 0 bp when annotating a plant genome. I agree that the `buildSummary.pl` provides more detailed and reasonable summary of repeats.

For the overlapping issue, it turns out that I found a solution, which is to split the overlapping annotations and make sure each bp is annotated only once. Although the results don't change drastically, someone may find this type of annotation helpful. This will also result in a different gff3 output and located in `genome.mod.EDTA.anno/genome.mod.EDTA.TEanno.split.gff3`. The new update will be released soon.

For your fragmented genome annotation, because EDTA relies on structurally intact elements to construct TE libraries. If the genome is fragmented, there won't be a lot of intact elements available and thus the sensitivity will be decreased. RepeatMasker uses other TE libraries to identify TEs and probably there is a sister species in its library.

Best,
Shujun

**Comment by biolittleboy** [comment]
Thank you again for your patient explanation. As you say, there is a de novo TE dataset detected by RepeatModeler in the library of RepeatMasker. I am looking forward to the release of the new version.
I will close this question. Have a nice day!
